### ISSUE TITLE
how to extract the numerical part from a physical constant

### ISSUE THREAD

**Issue by thudjx** [JuliaPhysics/PhysicalConstants.jl#21]
I want to use the phyical constants without units in my calculations, but dont know how to achieve this. How can I access the pure numerical part, just as `import scipy.constants as C; C.e` in python?

**Comment by giordano** [comment]
> I want to use the phyical constants without units in my calculations

That's quite bold :slightly_smiling_face: 

I guess you want to use [`ustrip`](https://painterqubits.github.io/Unitful.jl/stable/manipulations/#Unitful.ustrip):
```julia
julia> using PhysicalConstants.CODATA2018, Unitful

julia> ustrip(u"m/s", SpeedOfLightInVacuum)
2.99792458e8
```
