### ISSUE TITLE
Unable to install on fresh julia 1.6/1.7 installs

### ISSUE THREAD

**Issue by jmmshn** [JuliaPhysics/PhysicalConstants.jl#24]
Dear maintainers,
This looks like a super useful package for science and I'm trying to install it.
I tried a few ways using different versions of Julia but keep running into the same problem:

![image](https://user-images.githubusercontent.com/14003693/187970361-12894916-a518-409c-9095-ac84f05bb802.png)

I'm kind of a Julia noob so please let me know if I'm doing something really silly.

Thanks in advance!

**Comment by giordano** [comment]
Can you please come back to the normal Julia REPL (press Ctrl + C) and run
```julia
using PhysicalConstants
```
after you get that error, to show the full error message?  This is what is suggested in the last line with "load the package" (packages in Julia are loaded with `using ...`).

**Comment by jmmshn** [comment]
Oh yeah, I should have probably included that.

Here is it:

![image](https://user-images.githubusercontent.com/14003693/187975579-dceae92b-7bdb-4880-b1d8-2730b1cddf9f.png)

**Comment by giordano** [comment]
Oh, cool, it looks like you tried to install the package right after https://github.com/JuliaPhysics/Measurements.jl/pull/118 was merged and accidentally broke this package, I'll have to fix that

**Comment by jmmshn** [comment]
OK, I actually look at `Measurements.tag_counters` and did not notice the missing `s`.
Thanks for your help!
I'll keep an eye out for the new release.

**Comment by giordano** [comment]
Version [0.2.3](https://github.com/JuliaPhysics/PhysicalConstants.jl/releases/tag/v0.2.3) is now out.  If you update the registry (`]up`) you should get the latest version of this package, which fixes compatibility with `Measurements.jl`.  Unfortunately this package sneakingly uses some internal structures of `Measurements.jl` which aren't part of the public API, which however were changed in the PR linked above and broke this package as a side effect.  That's on me for using internals of other packages, but at least I maintain both of them :slightly_smiling_face:   Also, it doesn't look like other packages are referencing [`Measurements.tag_counters`](https://juliahub.com/ui/Search?type=code&q=tag_counters&r=true), so it should be all good now.  Thanks for the report!
