### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPhysics/PhysicalConstants.jl#3]
When I try to use it right now, I get
```
(v1.0) pkg> resolve
 Resolving package versions...
PhysicalConstants [22bc3fda] log:
 ├─PhysicalConstants [22bc3fda] has no known versions!
```

**Comment by giordano** [comment]
I know, this is not registered yet because I'd like first to sort out the issues at #1 and #2.  As written in the [`README.md`](https://github.com/JuliaPhysics/PhysicalConstants.jl/tree/1ece2d178a2b8af6d8007b4e52f37807b4d0dfd0#installation), you should be able to install it with
```
pkg> add https://github.com/JuliaPhysics/PhysicalConstants.jl
```

**Comment by BeastyBlacksmith** [comment]
I did add it, but I can't precompile a Package that depends on it

**Comment by giordano** [comment]
Oh, I see the problem.  Ok, then I'll tag a very alpha version.

**Comment by BeastyBlacksmith** [comment]
Hmm... maybe its Pkg. After adding it to the `(1.0)` environment, in addition to the project environment, I spits a lot of warnings, but it works

**Comment by giordano** [comment]
If you're using a `Project.toml` file you should be able to add a non-registered package as dependence (but I don't know exactly how to do this).  If you're using only a `REQUIRE` file I think it'll be impossible to load a non-registered package inside your one.

**Comment by giordano** [comment]
Version v0.1.0 is now in `METADATA.jl` :smiley:
