### ISSUE TITLE
Add CODATA2018

### ISSUE THREAD

**Issue by Paalon** [JuliaPhysics/PhysicalConstants.jl#5]
CODATA2018 will be available 20 May 2019.

> The next regular CODATA four year cycle adjustment of the fundamental constants will be the 2018 adjustment with a closing date for input data of 31 December, 2018, with the relevant data in publication or preprint form as usual.  The results will be made available by 20 May 2019 (World Metrology Day) when the revised SI is to be implemented.  The 2018 CODATA adjustment is unique in that it will be the first adjustment of the fundamental constants in the revised SI with much more accurate values for almost all the fundamental constants.

http://www.codata.org/committees-and-groups/fundamental-physical-constants

**Comment by Paalon** [comment]
It's the day. 2018 CODATA adjustment values are available.
https://physics.nist.gov/cuu/Constants/Table/allascii.txt

**Comment by giordano** [comment]
Cool, thanks!  I'll see to update the package in the next few days

**Comment by giordano** [comment]
This is interesting: vacuum electric permittivity and vacuum mag. permeability are no more exact :confused:

**Comment by giordano** [comment]
I've opened a draft pull request at #13, but there are a lot of things to fix
